# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GuiaDeCampo
                                 A QGIS plugin
 Geração de PDFs com hiperlinks georreferenciados.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-18
        copyright            : (C) 2026 by FARM Analytica
        email                : caio.arantes@farmanaltyica.com.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GuiaDeCampo class from file GuiaDeCampo.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .guia_de_campo import GuiaDeCampo
    return GuiaDeCampo(iface)
