# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GuiaDeCampoDialog
                                 A QGIS plugin
 Gerao de PDFs com hiperlinks georreferenciados.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-18
        git sha              : $Format:%H$
        copyright            : (C) 2026 by FARM Analytica
        email                : caio.arantes@farmanaltyica.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtCore, QtGui, QtWidgets


def _qt_class_enum(qt_class, scoped_name, member_name, legacy_name):
    """Return a Qt5/Qt6 compatible enum member from a Qt class."""
    scoped_enum = getattr(qt_class, scoped_name, None)
    if scoped_enum is not None:
        return getattr(scoped_enum, member_name)
    return getattr(qt_class, legacy_name)


def _qt_enum(scoped_name, member_name, legacy_name):
    """Return a Qt5/Qt6 compatible enum member."""
    scoped_enum = getattr(QtCore.Qt, scoped_name, None)
    if scoped_enum is not None:
        return getattr(scoped_enum, member_name)
    return getattr(QtCore.Qt, legacy_name)


def _widget_enum(widget_class, scoped_name, member_name, legacy_name):
    """Return a Qt5/Qt6 compatible enum member from a widget class."""
    return _qt_class_enum(widget_class, scoped_name, member_name, legacy_name)


def _palette_role(member_name, legacy_name):
    """Return a QPalette color role compatible with Qt5 and Qt6."""
    return _qt_class_enum(QtGui.QPalette, 'ColorRole', member_name, legacy_name)


def _event_type(member_name, legacy_name):
    """Return a QEvent type compatible with Qt5 and Qt6."""
    return _qt_class_enum(QtCore.QEvent, 'Type', member_name, legacy_name)


def _color_to_hex(color):
    """Return a stylesheet-ready RGB color string."""
    return color.name()


def _blend_colors(color_a, color_b, ratio):
    """Blend two colors using the provided ratio for color_b."""
    ratio = max(0.0, min(1.0, ratio))
    inverse = 1.0 - ratio
    return QtGui.QColor(
        int(color_a.red() * inverse + color_b.red() * ratio),
        int(color_a.green() * inverse + color_b.green() * ratio),
        int(color_a.blue() * inverse + color_b.blue() * ratio),
    )


def _css_block(selector, *rules):
    """Build a stylesheet block without f-string brace escaping issues."""
    body = '\n'.join('            ' + rule for rule in rules)
    return '{} {{\n{}\n        }}'.format(selector, body)


class GuiaDeCampoDialog(QtWidgets.QDialog):
    """Main plugin dialog built in code (no .ui dependency)."""

    def __init__(self, plugin_language='en', parent=None):
        """Create all controls used by service actions."""
        super(GuiaDeCampoDialog, self).__init__(parent)
        self.plugin_language = plugin_language
        self._refreshing_stylesheet = False
        self._current_point_count = 0

        self.setWindowTitle(self._t('Field Guide', 'Field Guide'))
        self.setWindowFlag(_qt_enum('WindowType', 'WindowStaysOnTopHint', 'WindowStaysOnTopHint'), True)
        self.setWindowFlag(_qt_enum('WindowType', 'WindowMinimizeButtonHint', 'WindowMinimizeButtonHint'), True)
        self.resize(560, 720)
        self.setMinimumSize(520, 640)
        self.setStyleSheet(self._build_stylesheet())

        root_layout = QtWidgets.QVBoxLayout(self)
        root_layout.setContentsMargins(12, 10, 12, 10)
        root_layout.setSpacing(10)

        scroll_area = QtWidgets.QScrollArea(self)
        scroll_area.setWidgetResizable(True)
        scroll_area.setFrameShape(_widget_enum(QtWidgets.QFrame, 'Shape', 'NoFrame', 'NoFrame'))
        root_layout.addWidget(scroll_area)

        content = QtWidgets.QWidget(self)
        scroll_area.setWidget(content)

        layout = QtWidgets.QVBoxLayout(content)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(10)

        self._build_header(layout)
        self._build_capture_group(layout)
        self._build_state_group(layout)
        self._build_manual_group(layout)
        self._build_manage_group(layout)
        self._build_output_group(layout)
        self._build_about_group(layout)
        layout.addStretch(1)

        self.mark_on_canvas_checkbox.toggled.connect(self.update_capture_status)
        self.centroid_layer_combo.currentIndexChanged.connect(self._update_centroid_action_state)
        self.samples_per_feature_spinbox.valueChanged.connect(self._update_sampling_controls)
        self.sample_distribution_combo.currentIndexChanged.connect(self._update_sampling_controls)
        self.points_list_widget.itemSelectionChanged.connect(self._on_points_selection_changed)
        self.update_capture_status(self.mark_on_canvas_checkbox.isChecked())
        self.set_polygon_layers([])
        self._update_sampling_controls()
        self.set_points([])

    def _build_stylesheet(self):
        """Return dialog stylesheet."""
        palette = self.palette()
        window = palette.color(_palette_role('Window', 'Window'))
        base = palette.color(_palette_role('Base', 'Base'))
        alt_base = palette.color(_palette_role('AlternateBase', 'AlternateBase'))
        text = palette.color(_palette_role('WindowText', 'WindowText'))
        button = palette.color(_palette_role('Button', 'Button'))
        button_text = palette.color(_palette_role('ButtonText', 'ButtonText'))
        highlight = palette.color(_palette_role('Highlight', 'Highlight'))
        highlighted_text = palette.color(_palette_role('HighlightedText', 'HighlightedText'))
        link = palette.color(_palette_role('Link', 'Link'))
        mid = palette.color(_palette_role('Mid', 'Mid'))
        is_dark = window.lightnessF() < 0.5

        dialog_bg = _blend_colors(window, base, 0.18 if is_dark else 0.35)
        panel_bg = _blend_colors(base, window, 0.16 if is_dark else 0.06)
        panel_border = _blend_colors(mid, text, 0.18 if is_dark else 0.10)
        subtle_text = _blend_colors(text, window, 0.32 if is_dark else 0.42)
        muted_text = _blend_colors(text, window, 0.48 if is_dark else 0.58)
        button_bg = _blend_colors(button, base, 0.30 if is_dark else 0.18)
        button_hover = _blend_colors(button_bg, highlight, 0.14 if is_dark else 0.10)
        button_pressed = _blend_colors(button_bg, highlight, 0.24 if is_dark else 0.18)
        input_bg = _blend_colors(base, window, 0.08 if is_dark else 0.0)
        list_bg = _blend_colors(alt_base, base, 0.30 if is_dark else 0.70)
        separator = _blend_colors(panel_border, window, 0.20 if is_dark else 0.10)
        title_chip_bg = _blend_colors(dialog_bg, panel_bg, 0.55 if is_dark else 0.75)
        status_inactive_bg = _blend_colors(window, button, 0.45 if is_dark else 0.70)
        status_inactive_border = _blend_colors(panel_border, button_text, 0.20)
        success = QtGui.QColor('#4fd1c5' if is_dark else '#2f855a')
        success_bg = _blend_colors(base, success, 0.20 if is_dark else 0.12)
        success_border = _blend_colors(panel_border, success, 0.45)
        info = QtGui.QColor('#63b3ed' if is_dark else '#3182ce')
        warning = QtGui.QColor('#f6ad55' if is_dark else '#b7791f')
        danger = QtGui.QColor('#fc8181' if is_dark else '#c53030')
        neutral_green = QtGui.QColor('#68d391' if is_dark else '#2f855a')

        blocks = [
            _css_block(
                'QDialog',
                'background: {};'.format(_color_to_hex(dialog_bg)),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block('QScrollArea', 'background: transparent;'),
            _css_block('QLabel', 'color: {};'.format(_color_to_hex(text))),
            _css_block(
                'QLabel#titleLabel',
                'font-size: 20px;',
                'font-weight: 700;',
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QLabel#descriptionLabel',
                'color: {};'.format(_color_to_hex(subtle_text)),
                'line-height: 1.4;',
            ),
            _css_block(
                'QLabel#websiteLabel',
                'color: {};'.format(_color_to_hex(link)),
                'font-size: 11px;',
                'font-weight: 600;',
            ),
            _css_block(
                'QLabel#sectionHintLabel',
                'color: {};'.format(_color_to_hex(subtle_text)),
                'font-size: 11px;',
            ),
            _css_block(
                'QLabel#statusBadge',
                'border-radius: 11px;',
                'padding: 4px 10px;',
                'font-size: 11px;',
                'font-weight: 700;',
            ),
            _css_block(
                'QLabel#statusBadge[inactive="true"]',
                'background: {};'.format(_color_to_hex(status_inactive_bg)),
                'color: {};'.format(_color_to_hex(subtle_text)),
                'border: 1px solid {};'.format(_color_to_hex(status_inactive_border)),
            ),
            _css_block(
                'QLabel#statusBadge[inactive="false"]',
                'background: {};'.format(_color_to_hex(success_bg)),
                'color: {};'.format(_color_to_hex(text)),
                'border: 1px solid {};'.format(_color_to_hex(success_border)),
            ),
            _css_block(
                'QGroupBox',
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
                'border-radius: 12px;',
                'margin-top: 18px;',
                'padding-top: 16px;',
                'font-weight: 700;',
                'background: {};'.format(_color_to_hex(panel_bg)),
            ),
            _css_block(
                'QGroupBox::title',
                'subcontrol-origin: margin;',
                'subcontrol-position: top left;',
                'left: 12px;',
                'top: -2px;',
                'padding: 2px 8px;',
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
                'border-radius: 7px;',
                'background: {};'.format(_color_to_hex(title_chip_bg)),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton',
                'min-height: 32px;',
                'border-radius: 8px;',
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
                'padding: 5px 10px;',
                'font-weight: 600;',
                'background-color: {};'.format(_color_to_hex(button_bg)),
                'color: {};'.format(_color_to_hex(button_text)),
            ),
            _css_block('QPushButton:hover', 'background-color: {};'.format(_color_to_hex(button_hover))),
            _css_block('QPushButton:pressed', 'background-color: {};'.format(_color_to_hex(button_pressed))),
            _css_block(
                'QPushButton:disabled',
                'color: {};'.format(_color_to_hex(muted_text)),
                'background-color: {};'.format(_color_to_hex(panel_bg)),
                'border-color: {};'.format(_color_to_hex(separator)),
            ),
            _css_block(
                'QPushButton#hybridButton',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, neutral_green, 0.18 if is_dark else 0.10))),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(panel_border, neutral_green, 0.50))),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton#hybridButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, neutral_green, 0.28 if is_dark else 0.16))),
            ),
            _css_block(
                'QPushButton#routeAllButton',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, success, 0.20 if is_dark else 0.11))),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(panel_border, success, 0.52))),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton#routeAllButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, success, 0.30 if is_dark else 0.18))),
            ),
            _css_block(
                'QPushButton#clearButton',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, danger, 0.18 if is_dark else 0.10))),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(panel_border, danger, 0.55))),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton#clearButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, danger, 0.28 if is_dark else 0.16))),
            ),
            _css_block(
                'QPushButton#removeLastButton',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, warning, 0.18 if is_dark else 0.10))),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(panel_border, warning, 0.50))),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton#removeLastButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, warning, 0.28 if is_dark else 0.16))),
            ),
            _css_block(
                'QPushButton#deleteSelectedButton',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, info, 0.16 if is_dark else 0.10))),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(panel_border, info, 0.50))),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton#deleteSelectedButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, info, 0.26 if is_dark else 0.16))),
            ),
            _css_block(
                'QPushButton#csvExportButton',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, success, 0.16 if is_dark else 0.09))),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(panel_border, success, 0.46))),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton#csvExportButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, success, 0.25 if is_dark else 0.14))),
            ),
            _css_block(
                'QPushButton#csvImportButton',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, warning, 0.15 if is_dark else 0.09))),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(panel_border, warning, 0.45))),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton#csvImportButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, warning, 0.24 if is_dark else 0.14))),
            ),
            _css_block(
                'QPushButton#generateButton',
                'background-color: {};'.format(_color_to_hex(highlight)),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(highlight, panel_border, 0.20))),
                'color: {};'.format(_color_to_hex(highlighted_text)),
            ),
            _css_block(
                'QPushButton#generateButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(highlight, info, 0.18))),
            ),
            _css_block(
                'QPushButton#generateButton:pressed',
                'background-color: {};'.format(_color_to_hex(_blend_colors(highlight, text, 0.20 if is_dark else 0.10))),
            ),
            _css_block(
                'QPushButton#manualAddButton',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, info, 0.16 if is_dark else 0.10))),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(panel_border, info, 0.48))),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton#manualAddButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, info, 0.26 if is_dark else 0.16))),
            ),
            _css_block(
                'QPushButton#centroidButton',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, info, 0.18 if is_dark else 0.11))),
                'border: 1px solid {};'.format(_color_to_hex(_blend_colors(panel_border, info, 0.52))),
                'color: {};'.format(_color_to_hex(text)),
            ),
            _css_block(
                'QPushButton#centroidButton:hover',
                'background-color: {};'.format(_color_to_hex(_blend_colors(base, info, 0.28 if is_dark else 0.17))),
            ),
            _css_block(
                'QCheckBox',
                'spacing: 6px;',
                'color: {};'.format(_color_to_hex(text)),
                'font-weight: 600;',
                'padding: 2px 2px;',
            ),
            _css_block(
                'QCheckBox::indicator',
                'width: 18px;',
                'height: 18px;',
                'border-radius: 4px;',
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
                'background: {};'.format(_color_to_hex(input_bg)),
            ),
            _css_block(
                'QCheckBox::indicator:hover',
                'border: 1px solid {};'.format(_color_to_hex(highlight)),
                'background: {};'.format(_color_to_hex(_blend_colors(input_bg, highlight, 0.14 if is_dark else 0.08))),
            ),
            _css_block(
                'QCheckBox::indicator:checked',
                'border: 1px solid {};'.format(_color_to_hex(highlight)),
                'background: {};'.format(_color_to_hex(highlight)),
                'image: url(:/images/themes/default/mIconSuccess.svg);',
            ),
            _css_block(
                'QLineEdit',
                'min-height: 30px;',
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
                'border-radius: 8px;',
                'padding: 4px 8px;',
                'background: {};'.format(_color_to_hex(input_bg)),
                'color: {};'.format(_color_to_hex(text)),
                'selection-background-color: {};'.format(_color_to_hex(highlight)),
                'selection-color: {};'.format(_color_to_hex(highlighted_text)),
            ),
            _css_block('QLineEdit:focus', 'border: 1px solid {};'.format(_color_to_hex(highlight))),
            _css_block(
                'QComboBox',
                'min-height: 30px;',
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
                'border-radius: 8px;',
                'padding: 4px 8px;',
                'background: {};'.format(_color_to_hex(input_bg)),
                'color: {};'.format(_color_to_hex(text)),
                'selection-background-color: {};'.format(_color_to_hex(highlight)),
                'selection-color: {};'.format(_color_to_hex(highlighted_text)),
            ),
            _css_block('QComboBox:focus', 'border: 1px solid {};'.format(_color_to_hex(highlight))),
            _css_block(
                'QComboBox:disabled',
                'background: {};'.format(_color_to_hex(panel_bg)),
                'color: {};'.format(_color_to_hex(subtle_text)),
                'border-color: {};'.format(_color_to_hex(separator)),
            ),
            _css_block('QComboBox::drop-down', 'border: none;', 'width: 24px;'),
            _css_block(
                'QComboBox QAbstractItemView',
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
                'background: {};'.format(_color_to_hex(list_bg)),
                'color: {};'.format(_color_to_hex(text)),
                'selection-background-color: {};'.format(_color_to_hex(highlight)),
                'selection-color: {};'.format(_color_to_hex(highlighted_text)),
            ),
            _css_block(
                'QSpinBox',
                'min-height: 30px;',
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
                'border-radius: 8px;',
                'padding: 4px 8px;',
                'background: {};'.format(_color_to_hex(input_bg)),
                'color: {};'.format(_color_to_hex(text)),
                'selection-background-color: {};'.format(_color_to_hex(highlight)),
                'selection-color: {};'.format(_color_to_hex(highlighted_text)),
            ),
            _css_block('QSpinBox:focus', 'border: 1px solid {};'.format(_color_to_hex(highlight))),
            _css_block(
                'QSpinBox:disabled',
                'background: {};'.format(_color_to_hex(panel_bg)),
                'color: {};'.format(_color_to_hex(subtle_text)),
                'border-color: {};'.format(_color_to_hex(separator)),
            ),
            _css_block(
                'QListWidget',
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
                'border-radius: 10px;',
                'background: {};'.format(_color_to_hex(list_bg)),
                'color: {};'.format(_color_to_hex(text)),
                'padding: 4px;',
            ),
            _css_block(
                'QListWidget:disabled',
                'background: {};'.format(_color_to_hex(list_bg)),
                'color: {};'.format(_color_to_hex(subtle_text)),
                'border: 1px solid {};'.format(_color_to_hex(panel_border)),
            ),
            _css_block(
                'QListWidget::item',
                'padding: 7px 8px;',
                'margin: 2px 0;',
                'border-radius: 6px;',
            ),
            _css_block(
                'QListWidget::item:selected',
                'background: {};'.format(_color_to_hex(highlight)),
                'color: {};'.format(_color_to_hex(highlighted_text)),
            ),
            _css_block(
                'QFrame#lineSeparator',
                'background: {};'.format(_color_to_hex(separator)),
                'max-height: 1px;',
            ),
        ]
        return '\n'.join(blocks)

    def changeEvent(self, event):
        """Refresh the stylesheet when the application palette changes."""
        if (
            not self._refreshing_stylesheet
            and event.type() in (
                _event_type('PaletteChange', 'PaletteChange'),
                _event_type('ApplicationPaletteChange', 'ApplicationPaletteChange'),
            )
        ):
            self._refreshing_stylesheet = True
            try:
                self.setStyleSheet(self._build_stylesheet())
            finally:
                self._refreshing_stylesheet = False
        super(GuiaDeCampoDialog, self).changeEvent(event)

    def _build_header(self, layout):
        """Build top header area."""
        title_label = QtWidgets.QLabel(self._t('Field Guide', 'Field Guide'), self)
        title_label.setObjectName('titleLabel')
        layout.addWidget(title_label)

        description = QtWidgets.QLabel(
            self._t(
                'Capture points on the map, mark centroids from project layers, review them in a live list, and export routes or PDF outputs when ready.',
                'Capture pontos no mapa, marque centroides de camadas do projeto, acompanhe a lista em tempo real e exporte rotas ou PDFs quando estiver pronto.',
            ),
            self,
        )
        description.setObjectName('descriptionLabel')
        description.setWordWrap(True)
        layout.addWidget(description)

        website_label = QtWidgets.QLabel(self)
        website_label.setObjectName('websiteLabel')
        website_label.setText(
            self._t(
                'Project website: <a href="https://farmanalytica.github.io/fieldguide/">farmanalytica.github.io/fieldguide</a>',
                'Site do projeto: <a href="https://farmanalytica.github.io/fieldguide/">farmanalytica.github.io/fieldguide</a>',
            )
        )
        website_label.setTextFormat(_qt_enum('TextFormat', 'RichText', 'RichText'))
        website_label.setOpenExternalLinks(True)
        website_label.setWordWrap(True)
        layout.addWidget(website_label)

    def _build_capture_group(self, layout):
        """Build map capture section."""
        capture_group = QtWidgets.QGroupBox(
            self._t('Capture', 'Captura'),
            self,
        )
        capture_layout = QtWidgets.QVBoxLayout(capture_group)
        capture_layout.setContentsMargins(10, 12, 10, 10)
        capture_layout.setSpacing(8)

        capture_top_layout = QtWidgets.QHBoxLayout()
        capture_top_layout.setSpacing(8)

        self.mark_on_canvas_checkbox = QtWidgets.QCheckBox(
            self._t('Capture mode (click on map)', 'Modo de captura (clique no mapa)'),
            self,
        )
        capture_top_layout.addWidget(self.mark_on_canvas_checkbox, 1)

        self.capture_status_badge = QtWidgets.QLabel(self)
        self.capture_status_badge.setObjectName('statusBadge')
        capture_top_layout.addWidget(self.capture_status_badge, 0, _qt_enum('AlignmentFlag', 'AlignRight', 'AlignRight'))
        capture_layout.addLayout(capture_top_layout)

        capture_hint = QtWidgets.QLabel(
            self._t(
                'Use direct map clicks for field capture, or select a polygon layer below to generate marks inside each feature.',
                'Use cliques diretos no mapa para coleta em campo, ou selecione uma camada poligonal abaixo para gerar marcações dentro de cada feição.',
            ),
            self,
        )
        capture_hint.setObjectName('sectionHintLabel')
        capture_hint.setWordWrap(True)
        capture_layout.addWidget(capture_hint)

        self.hybrid_layer_button = QtWidgets.QPushButton(
            self._t('Add Google Hybrid', 'Adicionar Google Hybrid'),
            self,
        )
        self.hybrid_layer_button.setObjectName('hybridButton')
        capture_layout.addWidget(self.hybrid_layer_button)

        centroid_separator = QtWidgets.QFrame(self)
        centroid_separator.setObjectName('lineSeparator')
        centroid_separator.setFrameShape(_widget_enum(QtWidgets.QFrame, 'Shape', 'HLine', 'HLine'))
        capture_layout.addWidget(centroid_separator)

        self.centroid_layer_hint_label = QtWidgets.QLabel(self)
        self.centroid_layer_hint_label.setObjectName('sectionHintLabel')
        self.centroid_layer_hint_label.setWordWrap(True)
        capture_layout.addWidget(self.centroid_layer_hint_label)

        centroid_layer_row = QtWidgets.QHBoxLayout()
        centroid_layer_row.setSpacing(8)
        centroid_layer_row.addWidget(
            QtWidgets.QLabel(self._t('Polygon layer', 'Camada poligonal'), self)
        )

        self.centroid_layer_combo = QtWidgets.QComboBox(self)
        self.centroid_layer_combo.setMinimumContentsLength(18)
        centroid_layer_row.addWidget(self.centroid_layer_combo, 1)
        capture_layout.addLayout(centroid_layer_row)

        sampling_settings_layout = QtWidgets.QGridLayout()
        sampling_settings_layout.setHorizontalSpacing(8)
        sampling_settings_layout.setVerticalSpacing(6)

        sampling_settings_layout.addWidget(
            QtWidgets.QLabel(self._t('Marks per feature', 'Marcações por feição'), self),
            0,
            0,
        )
        self.samples_per_feature_spinbox = QtWidgets.QSpinBox(self)
        self.samples_per_feature_spinbox.setRange(1, 10)
        self.samples_per_feature_spinbox.setValue(1)
        sampling_settings_layout.addWidget(self.samples_per_feature_spinbox, 0, 1)

        self.sample_distribution_label = QtWidgets.QLabel(
            self._t('Distribution method', 'Método de distribuição'),
            self,
        )
        sampling_settings_layout.addWidget(self.sample_distribution_label, 1, 0)

        self.sample_distribution_combo = QtWidgets.QComboBox(self)
        self.sample_distribution_combo.addItem(
            self._t('Spread optimized', 'Otimizado por distribuição'),
            'spread_optimized',
        )
        self.sample_distribution_combo.addItem(
            self._t('Systematic grid', 'Grade sistemática'),
            'systematic_grid',
        )
        self.sample_distribution_combo.addItem(
            self._t('Zigzag transect', 'Transecto em zig-zag'),
            'zigzag_transect',
        )
        sampling_settings_layout.addWidget(self.sample_distribution_combo, 1, 1)
        capture_layout.addLayout(sampling_settings_layout)

        self.sample_distribution_hint_label = QtWidgets.QLabel(self)
        self.sample_distribution_hint_label.setObjectName('sectionHintLabel')
        self.sample_distribution_hint_label.setWordWrap(True)
        capture_layout.addWidget(self.sample_distribution_hint_label)

        self.mark_layer_centroids_button = QtWidgets.QPushButton(
            self._t('Mark feature centroids', 'Marcar centroides das feições'),
            self,
        )
        self.mark_layer_centroids_button.setObjectName('centroidButton')
        capture_layout.addWidget(self.mark_layer_centroids_button)
        layout.addWidget(capture_group)

    def _build_state_group(self, layout):
        """Build session state section."""
        state_group = QtWidgets.QGroupBox(
            self._t('Session State', 'Estado da Sessão'),
            self,
        )
        state_layout = QtWidgets.QVBoxLayout(state_group)
        state_layout.setContentsMargins(10, 12, 10, 10)
        state_layout.setSpacing(8)

        summary_grid = QtWidgets.QGridLayout()
        summary_grid.setHorizontalSpacing(8)
        summary_grid.setVerticalSpacing(6)

        summary_grid.addWidget(QtWidgets.QLabel(self._t('Points', 'Pontos'), self), 0, 0)
        self.point_count_value_label = QtWidgets.QLabel('0', self)
        summary_grid.addWidget(self.point_count_value_label, 0, 1)

        summary_grid.addWidget(QtWidgets.QLabel(self._t('Last point', 'Último ponto'), self), 1, 0)
        self.last_point_value_label = QtWidgets.QLabel(
            self._t('No points yet', 'Nenhum ponto ainda'),
            self,
        )
        self.last_point_value_label.setWordWrap(True)
        summary_grid.addWidget(self.last_point_value_label, 1, 1)

        summary_grid.addWidget(QtWidgets.QLabel(self._t('Route readiness', 'Pronto para rota'), self), 2, 0)
        self.route_status_value_label = QtWidgets.QLabel(
            self._t('Add at least 2 points', 'Adicione ao menos 2 pontos'),
            self,
        )
        self.route_status_value_label.setWordWrap(True)
        summary_grid.addWidget(self.route_status_value_label, 2, 1)

        state_layout.addLayout(summary_grid)

        self.points_list_hint_label = QtWidgets.QLabel(
            self._t(
                'Captured points appear here in collection order.',
                'Os pontos capturados aparecem aqui na ordem de coleta.',
            ),
            self,
        )
        self.points_list_hint_label.setObjectName('sectionHintLabel')
        state_layout.addWidget(self.points_list_hint_label)

        self.points_list_widget = QtWidgets.QListWidget(self)
        self.points_list_widget.setSelectionMode(
            _widget_enum(
                QtWidgets.QAbstractItemView,
                'SelectionMode',
                'SingleSelection',
                'SingleSelection',
            )
        )
        self.points_list_widget.setMinimumHeight(170)
        state_layout.addWidget(self.points_list_widget)

        session_actions_layout = QtWidgets.QHBoxLayout()
        session_actions_layout.setSpacing(8)

        self.remove_last_mark_button = QtWidgets.QPushButton(
            self._t('Remove last mark', 'Remover última marcação'),
            self,
        )
        self.remove_last_mark_button.setObjectName('removeLastButton')
        session_actions_layout.addWidget(self.remove_last_mark_button)

        self.delete_selected_mark_button = QtWidgets.QPushButton(
            self._t('Delete selected mark', 'Excluir marcação selecionada'),
            self,
        )
        self.delete_selected_mark_button.setObjectName('deleteSelectedButton')
        session_actions_layout.addWidget(self.delete_selected_mark_button)

        self.clear_marks_button = QtWidgets.QPushButton(
            self._t('Clear marks', 'Limpar marcações'),
            self,
        )
        self.clear_marks_button.setObjectName('clearButton')
        session_actions_layout.addWidget(self.clear_marks_button)

        state_layout.addLayout(session_actions_layout)
        layout.addWidget(state_group)

    def _build_manual_group(self, layout):
        """Build manual WGS84 input section."""
        manual_group = QtWidgets.QGroupBox(
            self._t('Add Manual Coordinate (WGS84)', 'Adicionar Coordenada Manual (WGS84)'),
            self,
        )
        manual_layout = QtWidgets.QGridLayout(manual_group)
        manual_layout.setContentsMargins(10, 12, 10, 10)
        manual_layout.setHorizontalSpacing(8)
        manual_layout.setVerticalSpacing(6)

        manual_hint = QtWidgets.QLabel(
            self._t(
                'Accepts decimal coordinates with dot or comma separators.',
                'Aceita coordenadas decimais com separador por ponto ou virgula.',
            ),
            self,
        )
        manual_hint.setObjectName('sectionHintLabel')
        manual_hint.setWordWrap(True)
        manual_layout.addWidget(manual_hint, 0, 0, 1, 2)

        manual_layout.addWidget(QtWidgets.QLabel(self._t('Latitude', 'Latitude'), self), 1, 0)
        manual_layout.addWidget(QtWidgets.QLabel(self._t('Longitude', 'Longitude'), self), 1, 1)

        self.manual_latitude_input = QtWidgets.QLineEdit(self)
        self.manual_latitude_input.setPlaceholderText(
            self._t('Latitude (e.g.: -23.550520)', 'Latitude (ex.: -23.550520)')
        )
        manual_layout.addWidget(self.manual_latitude_input, 2, 0)

        self.manual_longitude_input = QtWidgets.QLineEdit(self)
        self.manual_longitude_input.setPlaceholderText(
            self._t('Longitude (e.g.: -46.633308)', 'Longitude (ex.: -46.633308)')
        )
        manual_layout.addWidget(self.manual_longitude_input, 2, 1)

        self.add_manual_coordinate_button = QtWidgets.QPushButton(
            self._t('Add coordinate', 'Adicionar coordenada'),
            self,
        )
        self.add_manual_coordinate_button.setObjectName('manualAddButton')
        manual_layout.addWidget(self.add_manual_coordinate_button, 3, 0, 1, 2)
        layout.addWidget(manual_group)

    def _build_manage_group(self, layout):
        """Build route section."""
        manage_group = QtWidgets.QGroupBox(
            self._t('Route', 'Rota'),
            self,
        )
        manage_layout = QtWidgets.QVBoxLayout(manage_group)
        manage_layout.setContentsMargins(10, 12, 10, 10)
        manage_layout.setSpacing(8)

        manage_hint = QtWidgets.QLabel(
            self._t(
                'Open the current route in Google Maps when at least 2 points exist.',
                'Abra a rota atual no Google Maps quando houver ao menos 2 pontos.',
            ),
            self,
        )
        manage_hint.setObjectName('sectionHintLabel')
        manage_hint.setWordWrap(True)
        manage_layout.addWidget(manage_hint)

        self.route_all_points_button = QtWidgets.QPushButton(
            self._t('Open route in Google Maps', 'Abrir rota no Google Maps'),
            self,
        )
        self.route_all_points_button.setObjectName('routeAllButton')
        manage_layout.addWidget(self.route_all_points_button)
        layout.addWidget(manage_group)

    def _build_output_group(self, layout):
        """Build import, export, and report section."""
        output_group = QtWidgets.QGroupBox(
            self._t('Import / Export', 'Importação / Exportação'),
            self,
        )
        output_layout = QtWidgets.QVBoxLayout(output_group)
        output_layout.setContentsMargins(10, 12, 10, 10)
        output_layout.setSpacing(8)

        output_hint = QtWidgets.QLabel(
            self._t(
                'Import coordinates from CSV, export the current session, or generate the field PDF report.',
                'Importe coordenadas de CSV, exporte a sessão atual ou gere o PDF de campo.',
            ),
            self,
        )
        output_hint.setObjectName('sectionHintLabel')
        output_hint.setWordWrap(True)
        output_layout.addWidget(output_hint)

        csv_actions_layout = QtWidgets.QHBoxLayout()
        csv_actions_layout.setSpacing(8)

        self.import_csv_button = QtWidgets.QPushButton(
            self._t('Import points CSV', 'Importar pontos CSV'),
            self,
        )
        self.import_csv_button.setObjectName('csvImportButton')
        csv_actions_layout.addWidget(self.import_csv_button)

        self.export_csv_button = QtWidgets.QPushButton(
            self._t('Export points CSV', 'Exportar pontos CSV'),
            self,
        )
        self.export_csv_button.setObjectName('csvExportButton')
        csv_actions_layout.addWidget(self.export_csv_button)

        output_layout.addLayout(csv_actions_layout)

        separator = QtWidgets.QFrame(self)
        separator.setObjectName('lineSeparator')
        separator.setFrameShape(_widget_enum(QtWidgets.QFrame, 'Shape', 'HLine', 'HLine'))
        output_layout.addWidget(separator)

        self.generate_pfd_button = QtWidgets.QPushButton(
            self._t('Generate PDF', 'Gerar PDF'),
            self,
        )
        self.generate_pfd_button.setObjectName('generateButton')
        output_layout.addWidget(self.generate_pfd_button)
        layout.addWidget(output_group)

    def _build_about_group(self, layout):
        """Build low-priority about section."""
        about_group = QtWidgets.QGroupBox(
            self._t('About', 'Sobre'),
            self,
        )
        about_layout = QtWidgets.QHBoxLayout(about_group)
        about_layout.setContentsMargins(10, 12, 10, 10)
        about_layout.setSpacing(10)

        sponsor_logo_label = QtWidgets.QLabel(self)
        align_left = _qt_enum('AlignmentFlag', 'AlignLeft', 'AlignLeft')
        align_top = _qt_enum('AlignmentFlag', 'AlignTop', 'AlignTop')
        sponsor_logo_label.setAlignment(align_left | align_top)
        sponsor_logo_path = os.path.join(os.path.dirname(__file__), 'farm_icon.png')
        sponsor_logo_pixmap = QtGui.QPixmap(sponsor_logo_path)
        if not sponsor_logo_pixmap.isNull():
            sponsor_logo_label.setPixmap(
                sponsor_logo_pixmap.scaled(
                    168,
                    48,
                    _qt_enum('AspectRatioMode', 'KeepAspectRatio', 'KeepAspectRatio'),
                    _qt_enum('TransformationMode', 'SmoothTransformation', 'SmoothTransformation'),
                )
            )
        sponsor_logo_label.setFixedSize(172, 52)
        about_layout.addWidget(sponsor_logo_label)

        project_note = QtWidgets.QLabel(self)
        project_note.setWordWrap(True)
        project_note.setText(
            self._t(
                'This is a free and open project, developed with support from <a href="https://farmanalytica.com.br">FARM Analytica</a>. Ask about exclusive custom commercial solutions.',
                'Este é um projeto gratuito e aberto, desenvolvido com o apoio da <a href="https://farmanalytica.com.br">FARM Analytica</a>. Fale conosco sobre soluções comerciais exclusivas e personalizadas.',
            )
        )
        project_note.setTextFormat(_qt_enum('TextFormat', 'RichText', 'RichText'))
        project_note.setOpenExternalLinks(True)
        project_note.setObjectName('sectionHintLabel')
        about_layout.addWidget(project_note, 1)
        layout.addWidget(about_group)

    def update_capture_status(self, enabled):
        """Show current capture mode status in the header badge."""
        self.capture_status_badge.setProperty('inactive', not enabled)
        self.capture_status_badge.setText(
            self._t('Capture ON', 'Captura ON')
            if enabled
            else self._t('Capture OFF', 'Captura OFF')
        )
        self.capture_status_badge.style().unpolish(self.capture_status_badge)
        self.capture_status_badge.style().polish(self.capture_status_badge)

    def set_polygon_layers(self, layer_options, selected_layer_id=None):
        """Populate the polygon-layer selector from current project layers."""
        if selected_layer_id is None:
            selected_layer_id = self.centroid_layer_combo.currentData()

        self.centroid_layer_combo.blockSignals(True)
        self.centroid_layer_combo.clear()

        if layer_options:
            for layer_name, layer_id in layer_options:
                self.centroid_layer_combo.addItem(layer_name, layer_id)

            selected_index = self.centroid_layer_combo.findData(selected_layer_id)
            if selected_index < 0:
                selected_index = 0
            self.centroid_layer_combo.setCurrentIndex(selected_index)
            self.centroid_layer_hint_label.setText(
                self._t(
                    'Select a polygon layer from the current project and generate marks inside each feature.',
                    'Selecione uma camada poligonal do projeto atual e gere marcações dentro de cada feição.',
                )
            )
        else:
            self.centroid_layer_combo.addItem(
                self._t('No polygon layers available', 'Nenhuma camada poligonal disponivel'),
                None,
            )
            self.centroid_layer_combo.setCurrentIndex(0)
            self.centroid_layer_hint_label.setText(
                self._t(
                    'Add a polygon or multipolygon vector layer to the project to enable centroid marking.',
                    'Adicione uma camada vetorial poligonal ou multipoligonal ao projeto para habilitar a marcação de centroides.',
                )
            )

        self.centroid_layer_combo.blockSignals(False)
        self._update_centroid_action_state()

    def _update_centroid_action_state(self):
        """Enable centroid action only when a valid project layer is selected."""
        selected_layer_id = self.centroid_layer_combo.currentData()
        self.mark_layer_centroids_button.setEnabled(bool(selected_layer_id))

    def sample_count_per_feature(self):
        """Return the requested number of marks per polygon feature."""
        return max(1, min(10, int(self.samples_per_feature_spinbox.value())))

    def sample_distribution_method(self):
        """Return the selected multi-point distribution method."""
        method = self.sample_distribution_combo.currentData()
        if not method:
            return 'spread_optimized'
        return method

    def _update_sampling_controls(self):
        """Refresh polygon sampling hints and control states."""
        sample_count = self.sample_count_per_feature()
        uses_centroid = sample_count == 1

        self.sample_distribution_label.setEnabled(not uses_centroid)
        self.sample_distribution_combo.setEnabled(not uses_centroid)

        if uses_centroid:
            self.sample_distribution_hint_label.setText(
                self._t(
                    'One mark per feature uses the polygon centroid, matching the current behavior.',
                    'Uma marcação por feição usa o centroide do polígono, mantendo o comportamento atual.',
                )
            )
            self.mark_layer_centroids_button.setText(
                self._t('Mark feature centroids', 'Marcar centroides das feições')
            )
        else:
            method = self.sample_distribution_method()
            if method == 'systematic_grid':
                hint_text = self._t(
                    'Places marks from a regular grid clipped to each polygon. Good for balanced field coverage and repeatable spacing.',
                    'Posiciona marcações a partir de uma grade regular recortada ao polígono. Bom para cobertura equilibrada e espaçamento repetível.',
                )
            elif method == 'zigzag_transect':
                hint_text = self._t(
                    'Builds a serpentine walk pattern across each polygon, similar to common zigzag soil sampling in the field.',
                    'Monta um percurso serpenteado em cada polígono, semelhante ao zigue-zague comum na amostragem de solo em campo.',
                )
            else:
                hint_text = self._t(
                    'Chooses marks that maximize spacing inside each polygon. Good default for irregular areas and strong spatial distribution.',
                    'Escolhe marcações que maximizam o espaçamento dentro de cada polígono. Bom padrão para áreas irregulares e boa distribuição espacial.',
                )
            self.sample_distribution_hint_label.setText(hint_text)
            self.mark_layer_centroids_button.setText(
                self._t('Mark feature samples', 'Marcar amostras por feição')
            )

        self._update_centroid_action_state()

    def set_points(self, coordinates):
        """Refresh the session summary and point list widgets."""
        coordinates = list(coordinates)
        point_count = len(coordinates)
        self._current_point_count = point_count
        self.point_count_value_label.setText(str(point_count))

        self.points_list_widget.clear()
        if point_count == 0:
            empty_text = self._t(
                'No points captured yet. Turn on capture mode, mark layer centroids, or add coordinates manually.',
                'Nenhum ponto capturado ainda. Ative o modo de captura, marque centroides de camada ou adicione coordenadas manualmente.',
            )
            empty_item = QtWidgets.QListWidgetItem(empty_text)
            empty_item.setFlags(
                empty_item.flags() & ~_qt_enum('ItemFlag', 'ItemIsSelectable', 'ItemIsSelectable')
            )
            self.points_list_widget.addItem(empty_item)
            self.points_list_widget.clearSelection()
            self.points_list_widget.setEnabled(True)
            self.last_point_value_label.setText(self._t('No points yet', 'Nenhum ponto ainda'))
            self.route_status_value_label.setText(
                self._t('Add at least 2 points', 'Adicione ao menos 2 pontos')
            )
        else:
            self.points_list_widget.setEnabled(True)
            for index, (longitude, latitude) in enumerate(coordinates, start=1):
                self.points_list_widget.addItem(
                    self._t(
                        'Point {index}: {lat:.6f}, {lon:.6f}',
                        'Ponto {index}: {lat:.6f}, {lon:.6f}',
                    ).format(index=index, lat=latitude, lon=longitude)
                )
            last_longitude, last_latitude = coordinates[-1]
            self.last_point_value_label.setText(
                '{:.6f}, {:.6f}'.format(last_latitude, last_longitude)
            )
            if point_count >= 2:
                self.route_status_value_label.setText(self._t('Ready', 'Pronto'))
            else:
                self.route_status_value_label.setText(
                    self._t('Add at least 2 points', 'Adicione ao menos 2 pontos')
                )

        self._update_action_states(point_count)

    def selected_point_index(self):
        """Return the selected point index from the live session list, if any."""
        if self._current_point_count <= 0:
            return -1

        selected_indexes = self.points_list_widget.selectedIndexes()
        if not selected_indexes:
            return -1

        selected_row = selected_indexes[0].row()
        if selected_row < 0 or selected_row >= self._current_point_count:
            return -1
        return selected_row

    def select_point_index(self, index):
        """Select a point row when it exists, otherwise clear the list selection."""
        if index < 0 or index >= self._current_point_count:
            self.points_list_widget.clearSelection()
            self.points_list_widget.setCurrentRow(-1)
            self._update_action_states(self._current_point_count)
            return

        self.points_list_widget.setCurrentRow(index)
        self._update_action_states(self._current_point_count)

    def _on_points_selection_changed(self):
        """Keep selection-dependent actions synced with the list widget state."""
        self._update_action_states(self._current_point_count)

    def _update_action_states(self, point_count):
        """Enable only actions that are valid for the current session state."""
        has_points = point_count > 0
        has_route = point_count >= 2
        has_selected_point = self.selected_point_index() >= 0
        self.remove_last_mark_button.setEnabled(has_points)
        self.delete_selected_mark_button.setEnabled(has_selected_point)
        self.clear_marks_button.setEnabled(has_points)
        self.export_csv_button.setEnabled(has_points)
        self.generate_pfd_button.setEnabled(has_points)
        self.route_all_points_button.setEnabled(has_route)

    def _t(self, english_text, portuguese_text):
        """Return pt-BR text only when plugin language is Portuguese."""
        if self.plugin_language == 'pt_BR':
            return portuguese_text
        return english_text
