# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GuiaDeCampo
                                 A QGIS plugin
 Geração de PDFs com hiperlinks georreferenciados.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-18
        git sha              : $Format:%H$
        copyright            : (C) 2026 by FARM Analytica
        email                : caio.arantes@farmanaltyica.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .guia_de_campo_dialog import GuiaDeCampoDialog
from .guia_de_campo_service import GuiaDeCampoService
import os.path


class GuiaDeCampo:
    """QGIS Plugin Implementation.

    This class wires the QGIS plugin lifecycle to the dialog and service layer.
    """

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.service = GuiaDeCampoService(self.iface)
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GuiaDeCampo_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&GuiaDeCampo')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GuiaDeCampo', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/guia_de_campo/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Guia de Campo'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&GuiaDeCampo'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Open plugin dialog and ensure UI signals are connected once."""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = GuiaDeCampoDialog()

            # Connect dialog controls to service methods once per QGIS session.
            self.dlg.hybrid_layer_button.clicked.connect(
                self.service.add_hybrid_layer
            )
            self.dlg.route_all_points_button.clicked.connect(
                self.service.open_all_points_route
            )
            self.dlg.clear_marks_button.clicked.connect(
                self.service.clear_marks
            )
            self.dlg.remove_last_mark_button.clicked.connect(
                self.service.remove_last_mark
            )
            self.dlg.generate_pfd_button.clicked.connect(
                self.service.generate_pfd
            )
            self.dlg.mark_on_canvas_checkbox.toggled.connect(
                self.service.toggle_mark_mode
            )
            self.dlg.add_manual_coordinate_button.clicked.connect(
                lambda: self.service.add_manual_coordinate(self.dlg)
            )
            self.dlg.export_csv_button.clicked.connect(
                self.service.export_marks_csv
            )
            self.dlg.import_csv_button.clicked.connect(
                self.service.import_marks_csv
            )
            self.dlg.finished.connect(
                lambda _: self.dlg.mark_on_canvas_checkbox.setChecked(False)
            )
            self.dlg.finished.connect(lambda _: self.service.disable_mark_mode())

        # Keep dialog modeless so user can interact with map canvas while open.
        self.dlg.show()
        self.dlg.raise_()
        self.dlg.activateWindow()
