# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GuiaDeCampoDialog
                                 A QGIS plugin
 Geração de PDFs com hiperlinks georreferenciados.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-18
        git sha              : $Format:%H$
        copyright            : (C) 2026 by FARM Analytica
        email                : caio.arantes@farmanaltyica.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt import QtCore, QtWidgets


class GuiaDeCampoDialog(QtWidgets.QDialog):
    """Main plugin dialog built in code (no .ui dependency)."""

    def __init__(self, parent=None):
        """Create all controls used by service actions."""
        super(GuiaDeCampoDialog, self).__init__(parent)
        self.setWindowTitle('Guia de Campo')
        self.setWindowFlag(QtCore.Qt.WindowStaysOnTopHint, True)
        self.resize(420, 160)

        layout = QtWidgets.QVBoxLayout(self)

        description = QtWidgets.QLabel(
            'Configure os parâmetros para gerar o PDF da Guia de Campo.', self
        )
        description.setWordWrap(True)
        layout.addWidget(description)

        self.mark_on_canvas_checkbox = QtWidgets.QCheckBox(
            'Marcar no mapa (cliques múltiplos)', self
        )
        layout.addWidget(self.mark_on_canvas_checkbox)

        self.hybrid_layer_button = QtWidgets.QPushButton(
            'Adicionar Google Hybrid', self
        )
        layout.addWidget(self.hybrid_layer_button)

        self.clear_marks_button = QtWidgets.QPushButton(
            'Limpar marcações', self
        )
        layout.addWidget(self.clear_marks_button)

        self.generate_pfd_button = QtWidgets.QPushButton(
            'Gerar PFD', self
        )
        layout.addWidget(self.generate_pfd_button)

        # Keep standard accept/reject actions for quick close/confirm.
        self.button_box = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel,
            parent=self,
        )
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)

        layout.addWidget(self.button_box)
